// <auto-generated />
using System;
using LakshBeautyStudio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LakshBeautyStudio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LakshBeautyStudio.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PreferredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PreferredTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Yes, we recommend booking in advance to ensure availability, especially for bridal services.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Question = "Do I need an appointment?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Yes, walk-ins are welcome subject to slot availability.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Question = "Is walk-in available?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Currently we offer bridal services at our studio. Please contact us for special requests.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Question = "Do you provide bridal service at home?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "We are open 9 AM to 2 PM and 3 PM to 7 PM, all days.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Question = "What are your working hours?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "You can book via our website form, WhatsApp, or by calling us directly.",
                            DisplayOrder = 5,
                            IsActive = true,
                            Question = "How do I book an appointment?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Yes, we have Basic, Premium, and Luxury bridal packages tailored to your needs.",
                            DisplayOrder = 6,
                            IsActive = true,
                            Question = "Do you offer bridal packages?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "We use premium quality, skin-friendly beauty products for all our services.",
                            DisplayOrder = 7,
                            IsActive = true,
                            Question = "What products do you use?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Yes, please contact us at least a few hours in advance to reschedule.",
                            DisplayOrder = 8,
                            IsActive = true,
                            Question = "Can I reschedule my appointment?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Yes, we have Hair Care Combo, Skin Glow Combo, and Nail Beauty Combo at special prices.",
                            DisplayOrder = 9,
                            IsActive = true,
                            Question = "Do you have combo offers?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Bridal packages require advance booking; please contact us for payment details.",
                            DisplayOrder = 10,
                            IsActive = true,
                            Question = "Is advance payment required for bridal bookings?"
                        });
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Studio Interior",
                            DisplayOrder = 1,
                            ImagePath = "https://images.pexels.com/photos/7750099/pexels-photo-7750099.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Reception Lobby",
                            DisplayOrder = 2,
                            ImagePath = "https://images.pexels.com/photos/7750119/pexels-photo-7750119.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Styling Area",
                            DisplayOrder = 3,
                            ImagePath = "https://images.pexels.com/photos/7750091/pexels-photo-7750091.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Makeup Station",
                            DisplayOrder = 4,
                            ImagePath = "https://images.pexels.com/photos/7750104/pexels-photo-7750104.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Salon Seating",
                            DisplayOrder = 5,
                            ImagePath = "https://images.pexels.com/photos/7750100/pexels-photo-7750100.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Caption = "Lounge Area",
                            DisplayOrder = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Caption = "Vanity Mirrors",
                            DisplayOrder = 7,
                            ImagePath = "https://images.pexels.com/photos/7750108/pexels-photo-7750108.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Caption = "Studio View",
                            DisplayOrder = 8,
                            ImagePath = "https://images.pexels.com/photos/7750116/pexels-photo-7750116.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Caption = "Elegant Interior",
                            DisplayOrder = 9,
                            ImagePath = "https://images.pexels.com/photos/7750120/pexels-photo-7750120.jpeg?auto=compress&cs=tinysrgb&w=800",
                            IsActive = true,
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Basic Bridal Package",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Premium Bridal Package",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Luxury Bridal Package",
                            Price = 29999m
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Pre-Bridal Package",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Engagement Package",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Reception Package",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Groom Package",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Couple Wedding Package",
                            Price = 24999m
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "Monthly Beauty Package",
                            Price = 2499m
                        });
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Hair Cut",
                            StartingPrice = 250m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Trim",
                            StartingPrice = 150m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Wash",
                            StartingPrice = 150m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Styling",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Hair Spa",
                            StartingPrice = 800m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Smoothening",
                            StartingPrice = 3500m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Straightening",
                            StartingPrice = 4000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Rebonding",
                            StartingPrice = 4500m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Keratin Treatment",
                            StartingPrice = 5000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Botox Treatment",
                            StartingPrice = 4500m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Coloring",
                            StartingPrice = 1200m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Highlights",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Balayage",
                            StartingPrice = 3000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Root Touch-up",
                            StartingPrice = 800m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Oil Massage",
                            StartingPrice = 300m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Fall Treatment",
                            StartingPrice = 800m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Dandruff Treatment",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Scalp Treatment",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hair Extensions",
                            StartingPrice = 3000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            ImagePath = "https://images.pexels.com/photos/367724/pexels-photo-367724.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Bridal Hair Styling",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Bridal Makeup",
                            StartingPrice = 8000m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "HD Bridal Makeup",
                            StartingPrice = 12000m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Airbrush Makeup",
                            StartingPrice = 15000m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Party Makeup",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Engagement Makeup",
                            StartingPrice = 5000m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Reception Makeup",
                            StartingPrice = 6000m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Sangeet Makeup",
                            StartingPrice = 4000m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Mehendi Makeup",
                            StartingPrice = 3000m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Fashion Makeup",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Photoshoot Makeup",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Natural Makeup",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            ImagePath = "https://images.pexels.com/photos/6161/makeup-make-up-artist-make-up.jpg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Groom Makeup",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Cleanup",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Fruit Facial",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Gold Facial",
                            StartingPrice = 1200m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Diamond Facial",
                            StartingPrice = 1800m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Pearl Facial",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "O3+ Facial",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Hydra Facial",
                            StartingPrice = 3000m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Anti-Aging Facial",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Acne Treatment Facial",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Skin Brightening Facial",
                            StartingPrice = 1800m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "De-Tan Treatment",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Bleach",
                            StartingPrice = 350m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            ImagePath = "https://images.pexels.com/photos/361755/pexels-photo-361755.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Face Polishing",
                            StartingPrice = 1000m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Manicure",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Spa Manicure",
                            StartingPrice = 900m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Pedicure",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Spa Pedicure",
                            StartingPrice = 1000m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Gel Nail Extensions",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Acrylic Nail Extensions",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Nail Art",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Gel Polish",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Nail Refill",
                            StartingPrice = 800m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Nail Repair",
                            StartingPrice = 300m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 4,
                            ImagePath = "https://images.pexels.com/photos/5484948/pexels-photo-5484948.png?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Nail Removal",
                            StartingPrice = 400m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Eyebrow Threading",
                            StartingPrice = 50m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Upper Lip Threading",
                            StartingPrice = 40m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Full Face Threading",
                            StartingPrice = 200m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Eyebrow Shaping",
                            StartingPrice = 100m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Eyebrow Tinting",
                            StartingPrice = 300m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Eyelash Extensions",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Lash Lift",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Lash Tint",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 5,
                            ImagePath = "https://images.pexels.com/photos/3885102/pexels-photo-3885102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Brow Lamination",
                            StartingPrice = 1200m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Full Arms Waxing",
                            StartingPrice = 400m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Half Arms Waxing",
                            StartingPrice = 250m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Full Legs Waxing",
                            StartingPrice = 600m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Half Legs Waxing",
                            StartingPrice = 350m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Underarm Waxing",
                            StartingPrice = 200m
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Full Body Waxing",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Chocolate Wax",
                            StartingPrice = 900m
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Rica Wax",
                            StartingPrice = 1000m
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Bikini Wax",
                            StartingPrice = 800m
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Body Polishing",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Body Scrub",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Body Spa",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Aroma Body Massage",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Deep Tissue Massage",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 6,
                            ImagePath = "https://images.pexels.com/photos/7750102/pexels-photo-7750102.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Hot Stone Massage",
                            StartingPrice = 2500m
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 7,
                            ImagePath = "https://images.pexels.com/photos/7750108/pexels-photo-7750108.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Skin Consultation",
                            StartingPrice = 200m
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 7,
                            ImagePath = "https://images.pexels.com/photos/7750108/pexels-photo-7750108.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Pigmentation Treatment",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 7,
                            ImagePath = "https://images.pexels.com/photos/7750108/pexels-photo-7750108.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Tan Removal",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 7,
                            ImagePath = "https://images.pexels.com/photos/7750108/pexels-photo-7750108.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Dark Circle Treatment",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 7,
                            ImagePath = "https://images.pexels.com/photos/7750108/pexels-photo-7750108.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Anti-Acne Treatment",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 7,
                            ImagePath = "https://images.pexels.com/photos/7750108/pexels-photo-7750108.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Skin Hydration Therapy",
                            StartingPrice = 2000m
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 8,
                            ImagePath = "https://images.pexels.com/photos/7750116/pexels-photo-7750116.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Kids Hair Cut",
                            StartingPrice = 150m
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 8,
                            ImagePath = "https://images.pexels.com/photos/7750116/pexels-photo-7750116.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Kids Party Hairstyle",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 8,
                            ImagePath = "https://images.pexels.com/photos/7750116/pexels-photo-7750116.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Birthday Makeup",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 8,
                            ImagePath = "https://images.pexels.com/photos/7750116/pexels-photo-7750116.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Graduation Makeup",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 8,
                            ImagePath = "https://images.pexels.com/photos/7750116/pexels-photo-7750116.jpeg?auto=compress&cs=tinysrgb&w=600",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Festive Makeup",
                            StartingPrice = 1500m
                        });
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Icon = "💇",
                            Name = "Hair Services"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Icon = "💄",
                            Name = "Makeup Services"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Icon = "🌸",
                            Name = "Facial & Skin Care"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Icon = "💅",
                            Name = "Nail Services"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Icon = "👁️",
                            Name = "Eye & Brow Services"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Icon = "🧖",
                            Name = "Body Care"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Icon = "✨",
                            Name = "Special Treatments"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Icon = "🧒",
                            Name = "Kids & Special Occasion"
                        });
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.Service", b =>
                {
                    b.HasOne("LakshBeautyStudio.Models.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LakshBeautyStudio.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
